"""Deterministic Abaqus Python export for confirmed STEP/CAD intent.

Mapping contract
----------------
Task 2 inventories the exact uploaded STEP file with OCC face tags.  Those
tags are CAD-side provenance only.  They are never consumed as solver face
IDs, solver face indexes, solver topology cardinality, solver set IDs, an
implicit ordinal offset, or proof that a CAD-to-solver correspondence exists.

The public adapter therefore has no CAD mapping at all and fails closed.  The
private renderer runs only when a caller supplies both an explicit solver
face mapping (``solver_face_ids_by_region``) and the solver-face universe
those IDs are drawn from (``solver_face_universe``).  The universe is a
renderer-owned solver topology contract supplied independently of any CAD
tag value; focused tests supply a clearly synthetic one.  R6 owns production
CAD-to-mesh/solver mapping.

Load mappings are explicit: resultant surface force is converted at script
execution time to an equal traction using the imported face area; pressure is
never used for that conversion.  Surface traction is emitted as traction,
pressure as pressure, and gravity as acceleration components.
"""

from __future__ import annotations

import json
import math
import re
from pathlib import Path

from ir.schema import SimulationIntent, region_entity_membership

from export.common import (
    CadModelMetadata,
    InvalidRegionReferenceError,
    MissingMaterialAssignmentError,
    MissingRegionMappingError,
    UnsupportedEntityTypeError,
    UnsupportedLoadTypeError,
    UnsupportedModelTypeError,
    ensure_export_ready,
    file_checksum,
    format_float,
    make_result,
    safe_artifact_stem,
    stable_name,
)


_HASH_RE = re.compile(r"^[0-9a-f]{64}$")
_AXIS_TO_DOF = {"x": 1, "y": 2, "z": 3}


def export_abaqus_py(intent: SimulationIntent, model: CadModelMetadata):
    """Public boundary: no CAD artifact exists before verified mesh mapping."""

    ensure_export_ready(intent)
    raise MissingRegionMappingError(
        "CAD-face export requires an exact artifact-backed solver mapping; "
        "source-local face tags are not authoritative."
    )


def _render_abaqus_py_with_verified_mapping(
    intent: SimulationIntent,
    model: CadModelMetadata,
    *,
    solver_face_ids_by_region: dict[str, tuple[int, ...]],
    solver_face_universe: tuple[int, ...],
):
    """Render below the mapping boundary using explicit solver face IDs.

    R4b.2's public adapter never calls this function.  Focused renderer tests
    supply a clearly synthetic mapping and a synthetic solver-face universe; a
    future mapping owner may call it only after independently verifying the
    CAD-to-solver correspondence.  Neither argument may be derived from the
    source CAD face tags carried on ``model`` or on the intent's regions.
    """

    report = ensure_export_ready(intent)
    region_names, material_names = _preflight(
        intent,
        model,
        solver_face_ids_by_region=solver_face_ids_by_region,
        solver_face_universe=solver_face_universe,
    )
    solver_face_ids = tuple(sorted(set(solver_face_universe)))

    warnings = [
        (
            "Solver faces are addressed only by the explicitly supplied solver face "
            "IDs. Source CAD face tags are retained as provenance and are not used "
            "as solver IDs, indexes, or topology counts; a verified CAD-to-solver "
            "mapping remains the caller's responsibility."
        ),
        (
            "The single IR material is assigned to all imported solid cells because the "
            "current IR has no per-region material-assignment field."
        ),
    ]
    if any(load.type == "resultant_surface_force" for load in intent.loads):
        warnings.append(
            "Resultant surface force is divided by imported face area inside the script "
            "and emitted as a general surface traction, never as pressure."
        )

    lines: list[str] = [
        "# Generated by sim-intent Task 14.",
        "# Inspect before use. Execution requires an Abaqus Python environment.",
        "# No solver job is created or submitted by this script.",
        "# Analysis: static_structural",
        "# Internal unit convention: mm-N-MPa (gravity acceleration in mm/s^2)",
        f"# Server-computed validation status: {report.validation_status}",
        f"# Source STEP SHA-256: {model.source_sha256}",
        "# Region mapping: explicit solver face IDs supplied by the caller below the public export gate.",
        "# Source CAD face tags are provenance only; they are not solver face IDs and imply no mapping.",
        "# Provenance is valid only for the exact content-hashed STEP file; regenerated CAD is unsupported.",
        "# Accepted assumptions:",
    ]
    accepted = sorted(
        (item for item in intent.assumptions if item.status == "accepted"),
        key=lambda item: item.id,
    )
    if accepted:
        for assumption in accepted:
            lines.append(f"# - [{assumption.id}] {_comment_string(assumption.text)}")
    else:
        lines.append("# - none")

    lines.extend(
        [
            "",
            "from abaqus import mdb",
            "from abaqusConstants import (DEFORMABLE_BODY, GENERAL, OFF, THREE_D,",
            "                             UNIFORM, UNSET)",
            "import math",
            "",
            "MODEL_NAME = 'SIM_INTENT_MODEL'",
            "PART_NAME = 'SIM_INTENT_PART'",
            "INSTANCE_NAME = 'SIM_INTENT_PART_1'",
            "STEP_NAME = 'STATIC_STEP'",
            f"STEP_FILE = {_python_string(model.source_name)}",
            f"SOURCE_STEP_SHA256 = {_python_string(model.source_sha256)}",
            "",
            "model = mdb.Model(name=MODEL_NAME)",
            "step_geometry = mdb.openStep(fileName=STEP_FILE, scaleFromFile=OFF)",
            "part = model.PartFromGeometryFile(",
            "    name=PART_NAME, geometryFile=step_geometry, combine=False,",
            "    dimensionality=THREE_D, type=DEFORMABLE_BODY)",
            f"# The supplied solver-face universe is 1..{max(solver_face_ids)}; it is not derived from CAD tags.",
            f"if len(part.faces) < {max(solver_face_ids)}:",
            "    raise RuntimeError('Imported face count cannot satisfy the supplied solver face universe.')",
            "",
        ]
    )

    for region in sorted(intent.regions, key=lambda item: item.id):
        set_name, surface_name = region_names[region.id]
        source_cad_face_tags = tuple(
            sorted(int(value) for value in region_entity_membership(region))
        )
        mapped_solver_face_ids = tuple(sorted(solver_face_ids_by_region[region.id]))
        tuple_text = _python_int_tuple(mapped_solver_face_ids)
        lines.extend(
            [
                f"# Region ID: {_comment_string(region.id)}",
                f"# source_instruction: {_comment_string(region.source_instruction)}",
                f"# source_cad_face_tags (provenance only, not solver IDs): "
                f"{json.dumps(list(source_cad_face_tags), separators=(',', ':'))}",
                f"# mapped_solver_face_ids (explicitly supplied): "
                f"{json.dumps(list(mapped_solver_face_ids), separators=(',', ':'))}",
                f"# selection_method: {region.selection_method}",
                f"# confidence: {format_float(region.confidence)}",
                f"# validation_status: {report.validation_status}",
                f"# solver_set: {set_name}; solver_surface: {surface_name}",
                f"_solver_face_ids = {tuple_text}",
                "_faces = tuple(part.faces[solver_face_id - 1]",
                "               for solver_face_id in _solver_face_ids)",
                f"part.Set(name='{set_name}', faces=_faces)",
                f"part.Surface(name='{surface_name}', side1Faces=_faces)",
                "",
            ]
        )

    for material in sorted(intent.materials, key=lambda item: (material_names[item.name], item.name)):
        solver_name = material_names[material.name]
        lines.extend(
            [
                f"# Material: {_comment_string(material.name)} ({material.model})",
                f"material = model.Material(name='{solver_name}')",
                f"material.Elastic(table=(({format_float(material.E_MPa)}, {format_float(material.nu)}),))",
            ]
        )
        if material.density_tonne_per_mm3 is not None:
            lines.append(
                "material.Density(table=(("
                f"{format_float(material.density_tonne_per_mm3)},),))"
            )
        lines.append("")

    sole_material = material_names[intent.materials[0].name]
    lines.extend(
        [
            "if len(part.cells) == 0:",
            "    raise RuntimeError('Imported STEP contains no solid cells for material assignment.')",
            "part.Set(name='ALL_SOLID_CELLS', cells=part.cells[:])",
            f"model.HomogeneousSolidSection(name='SECTION_ALL', material='{sole_material}', thickness=None)",
            "part.SectionAssignment(region=part.sets['ALL_SOLID_CELLS'], sectionName='SECTION_ALL')",
            "assembly = model.rootAssembly",
            "instance = assembly.Instance(name=INSTANCE_NAME, part=part, dependent=OFF)",
            "model.StaticStep(name=STEP_NAME, previous='Initial')",
            "",
        ]
    )

    sorted_bcs = sorted(
        enumerate(intent.bcs),
        key=lambda item: (
            item[1].type,
            item[1].region_ref,
            json.dumps(item[1].model_dump(mode="json"), sort_keys=True),
            item[0],
        ),
    )
    for ordinal, (_, bc) in enumerate(sorted_bcs, start=1):
        set_name = region_names[bc.region_ref][0]
        bc_name = f"BC_{ordinal:03d}_{bc.type.upper()}"
        values = {1: "UNSET", 2: "UNSET", 3: "UNSET"}
        if bc.type == "fixed_displacement":
            for axis in bc.components:
                values[_AXIS_TO_DOF[axis]] = "0.0"
        else:
            for axis, value in sorted(bc.components.items(), key=lambda item: _AXIS_TO_DOF[item[0]]):
                values[_AXIS_TO_DOF[axis]] = format_float(value)
        lines.extend(
            [
                f"# {bc.type} -> Abaqus DisplacementBC on region {bc.region_ref}",
                f"model.DisplacementBC(name='{bc_name}', createStepName=STEP_NAME,",
                f"    region=instance.sets['{set_name}'], u1={values[1]}, u2={values[2]}, u3={values[3]})",
                "",
            ]
        )

    sorted_loads = sorted(
        enumerate(intent.loads),
        key=lambda item: (
            item[1].type,
            item[1].region_ref or "",
            json.dumps(item[1].model_dump(mode="json"), sort_keys=True),
            item[0],
        ),
    )
    for ordinal, (_, load) in enumerate(sorted_loads, start=1):
        load_name = f"LOAD_{ordinal:03d}_{load.type.upper()}"
        if load.type == "resultant_surface_force":
            surface_name = region_names[load.region_ref][1]
            magnitude, direction = _magnitude_direction(load.vector)
            vector_text = ", ".join(format_float(value) for value in load.vector)
            direction_text = ", ".join(format_float(value) for value in direction)
            lines.extend(
                [
                    f"# resultant_surface_force on {load.region_ref}: total vector ({vector_text}) N",
                    "# Mapping: compute imported area at script runtime, then apply equal general traction.",
                    "# This is not a pressure conversion; vector direction is preserved.",
                    f"_surface = instance.surfaces['{surface_name}']",
                    "_surface_area = sum(face.getSize(printResults=False) for face in _surface.faces)",
                    "if _surface_area <= 0.0:",
                    "    raise RuntimeError('Confirmed resultant-force surface has non-positive area.')",
                    f"_traction_magnitude = {format_float(magnitude)} / _surface_area",
                    f"_traction_direction = ({direction_text})",
                    f"model.SurfaceTraction(name='{load_name}', createStepName=STEP_NAME,",
                    "    region=_surface, magnitude=_traction_magnitude, directionVector=((0.0, 0.0, 0.0), _traction_direction),",
                    "    distributionType=UNIFORM, traction=GENERAL)",
                    "",
                ]
            )
        elif load.type == "surface_traction":
            surface_name = region_names[load.region_ref][1]
            magnitude, direction = _magnitude_direction(load.vector)
            direction_text = ", ".join(format_float(value) for value in direction)
            lines.extend(
                [
                    f"# surface_traction on {load.region_ref}: vector components in MPa",
                    f"model.SurfaceTraction(name='{load_name}', createStepName=STEP_NAME,",
                    f"    region=instance.surfaces['{surface_name}'], magnitude={format_float(magnitude)},",
                    f"    directionVector=((0.0, 0.0, 0.0), ({direction_text})), distributionType=UNIFORM, traction=GENERAL)",
                    "",
                ]
            )
        elif load.type == "pressure":
            surface_name = region_names[load.region_ref][1]
            lines.extend(
                [
                    f"# pressure on {load.region_ref}: positive magnitude acts into the surface (Task 7 convention)",
                    f"model.Pressure(name='{load_name}', createStepName=STEP_NAME,",
                    f"    region=instance.surfaces['{surface_name}'], magnitude={format_float(load.magnitude)}, distributionType=UNIFORM)",
                    "",
                ]
            )
        elif load.type == "gravity":
            values = ", ".join(format_float(value) for value in load.vector)
            lines.extend(
                [
                    f"# gravity acceleration vector ({values}) mm/s^2",
                    f"model.Gravity(name='{load_name}', createStepName=STEP_NAME,",
                    "    region=instance.sets['ALL_SOLID_CELLS'],",
                    f"    comp1={format_float(load.vector[0])}, comp2={format_float(load.vector[1])}, comp3={format_float(load.vector[2])},",
                    "    distributionType=UNIFORM)",
                    "",
                ]
            )
        else:  # preflight rejects concentrated_force for current CAD entity vocabulary
            raise UnsupportedLoadTypeError(
                f"Abaqus Python mapping for load type '{load.type}' is unsupported."
            )

    text = "\n".join(lines).rstrip("\n") + "\n"
    filename = f"{safe_artifact_stem(model.source_name)}_abaqus.py"
    return make_result(
        adapter_name="abaqus_py",
        suggested_filename=filename,
        media_type="text/x-python; charset=utf-8",
        artifact_text=text,
        warnings=warnings,
    )


def _preflight(
    intent: SimulationIntent,
    model: CadModelMetadata,
    *,
    solver_face_ids_by_region: dict[str, tuple[int, ...]],
    solver_face_universe: tuple[int, ...],
) -> tuple[dict[str, tuple[str, str]], dict[str, str]]:
    suffix = Path(model.source_name).suffix.lower()
    if suffix not in {".step", ".stp"} or Path(model.source_name).name != model.source_name:
        raise UnsupportedModelTypeError("The abaqus_py adapter requires a safely named STEP model.")
    if model.source_path.suffix.lower() not in {".step", ".stp"}:
        raise UnsupportedModelTypeError("The explicit source path is not a STEP model.")
    if model.source_path.name != model.source_name:
        raise MissingRegionMappingError(
            "The explicit STEP path and source inventory name do not match."
        )
    if not _HASH_RE.fullmatch(model.source_sha256):
        raise MissingRegionMappingError("The STEP source content hash is missing or invalid.")
    if file_checksum(model.source_path) != model.source_sha256:
        raise MissingRegionMappingError(
            "The explicit STEP file no longer matches the grounded source content hash."
        )
    # The solver-face universe is the renderer's own solver topology contract.
    # It is supplied explicitly and is never inferred from CAD tag values, so
    # a large source tag can neither create nor enlarge a solver face.
    if any(
        isinstance(value, bool) or not isinstance(value, int)
        for value in solver_face_universe
    ):
        raise MissingRegionMappingError(
            "The solver-face universe must contain integer solver face IDs."
        )
    solver_face_ids = tuple(sorted(set(solver_face_universe)))
    if not solver_face_ids or solver_face_ids != tuple(
        range(1, max(solver_face_ids) + 1)
    ):
        raise MissingRegionMappingError(
            "The solver-face universe is not a contiguous solver face-ID sequence."
        )
    if len(intent.materials) != 1:
        raise MissingMaterialAssignmentError(
            "The current IR can assign material safely only when exactly one material applies to all solid cells."
        )
    expected_region_ids = {
        region.id for region in intent.regions if region.entity_type == "cad_face"
    }
    if set(solver_face_ids_by_region) != expected_region_ids:
        raise MissingRegionMappingError(
            "The verified solver mapping must cover every CAD region exactly."
        )

    region_names: dict[str, tuple[str, str]] = {}
    used_names: set[str] = set()
    for region in sorted(intent.regions, key=lambda item: item.id):
        if region.entity_type != "cad_face":
            raise UnsupportedEntityTypeError(
                f"The abaqus_py adapter supports cad_face regions, not '{region.entity_type}'."
            )
        mapped_ids = solver_face_ids_by_region[region.id]
        if any(
            isinstance(value, bool) or not isinstance(value, int)
            for value in mapped_ids
        ):
            raise InvalidRegionReferenceError(
                f"CAD region '{region.id}' must map to integer solver face IDs."
            )
        ids = [int(value) for value in mapped_ids]
        if len(ids) != len(set(ids)) or any(
            value not in solver_face_ids for value in ids
        ):
            raise InvalidRegionReferenceError(
                f"CAD region '{region.id}' maps to duplicate solver faces or to "
                "solver face IDs outside the supplied solver-face universe."
            )
        names = (stable_name("SET", region.id), stable_name("SURF", region.id))
        if any(name in used_names for name in names):
            raise MissingRegionMappingError("Two region IDs map to the same solver name.")
        used_names.update(names)
        region_names[region.id] = names

    material_names: dict[str, str] = {}
    for material in sorted(intent.materials, key=lambda item: item.name):
        solver_name = stable_name("MAT", material.name)
        if solver_name in used_names:
            raise MissingRegionMappingError("A material and region map to the same solver name.")
        used_names.add(solver_name)
        material_names[material.name] = solver_name

    for load in intent.loads:
        if load.type == "concentrated_force":
            raise UnsupportedLoadTypeError(
                "Concentrated force is not representable on the IR's CAD face/edge vocabulary; a vertex or reference point is required."
            )
        if load.type == "gravity" and load.region_ref is not None:
            raise UnsupportedEntityTypeError(
                "Region-scoped CAD gravity requires a solid-cell material region, which the current IR does not provide."
            )
    return region_names, material_names


def _magnitude_direction(vector: list[float]) -> tuple[float, tuple[float, float, float]]:
    magnitude = math.sqrt(sum(float(value) ** 2 for value in vector))
    return magnitude, tuple(float(value) / magnitude for value in vector)  # type: ignore[return-value]


def _python_int_tuple(values: tuple[int, ...]) -> str:
    body = ", ".join(str(value) for value in values)
    if len(values) == 1:
        body += ","
    return f"({body})"


def _python_string(value: str) -> str:
    return repr(value)


def _comment_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)
