"""Deterministic CalculiX/Abaqus INP fragment export (Task 14).

The adapter preserves native node/element identifiers and native NSET/ELSET
names from Task 5.  A ``mesh_face`` region means one or more Task 5 boundary
facet-group IDs.  Those groups carry faithful node membership, which is enough
for constraints and deterministic nodal force distribution.  They do not
carry owner-element/local-face labels; pressure therefore requires explicit
``element_face_by_facet`` metadata and otherwise fails rather than inventing
P1/P2/... labels.
"""

from __future__ import annotations

import json
import hashlib
import math
import re
from dataclasses import dataclass, replace
from decimal import Decimal, localcontext

from ir.schema import Region, SimulationIntent

from export.common import (
    ElementFaceReference,
    InvalidRegionReferenceError,
    MeshModelMetadata,
    MissingMaterialAssignmentError,
    MissingMeshTopologyError,
    MissingRegionMappingError,
    UnsupportedEntityTypeError,
    UnsupportedLoadTypeError,
    UnsupportedModelTypeError,
    ensure_export_ready,
    file_checksum,
    format_float,
    make_result,
    safe_artifact_stem,
    stable_name,
)


_SAFE_NATIVE_SET = re.compile(r"^[A-Za-z][A-Za-z0-9_]{0,79}$")
_AXIS_TO_DOF = {"x": 1, "y": 2, "z": 3}


@dataclass(frozen=True)
class _ResolvedRegion:
    region: Region
    set_name: str
    set_kind: str
    node_ids: tuple[int, ...] = ()
    element_ids: tuple[int, ...] = ()
    facet_ids: tuple[int, ...] = ()
    reuses_native_set: bool = False


def export_ccx_inp(intent: SimulationIntent, model: MeshModelMetadata):
    """Generate a solver-readable INP fragment without executing CalculiX."""

    report = ensure_export_ready(intent)
    resolved, material_name, all_elements_name, preflight_warnings = _preflight(
        intent, model
    )
    warnings = list(preflight_warnings)
    if any(load.type == "resultant_surface_force" for load in intent.loads):
        warnings.append(
            "Resultant surface force is equally distributed across sorted unique selected nodes; "
            "the final node receives the deterministic decimal remainder."
        )

    lines: list[str] = [
        "** Generated by sim-intent Task 14.",
        "** Inspect before use. This is an INP fragment for the exact source mesh.",
        "** No solver job was executed or submitted.",
        "** Analysis: static_structural",
        "** Internal unit convention: mm-N-MPa (gravity acceleration in mm/s^2)",
        f"** Server-computed validation status: {report.validation_status}",
        f"** Source mesh SHA-256: {model.inventory.file_sha256}",
        "** Accepted assumptions:",
    ]
    accepted = sorted(
        (item for item in intent.assumptions if item.status == "accepted"),
        key=lambda item: item.id,
    )
    if accepted:
        for assumption in accepted:
            lines.append(f"** - [{assumption.id}] {_comment_string(assumption.text)}")
    else:
        lines.append("** - none")
    lines.append("")

    for region_id in sorted(resolved):
        item = resolved[region_id]
        region = item.region
        lines.extend(
            [
                f"** Region ID: {_comment_string(region.id)}",
                f"** source_instruction: {_comment_string(region.source_instruction)}",
                f"** original_entity_ids: {json.dumps(region.entity_ids, separators=(',', ':'))}",
                f"** selection_method: {region.selection_method}",
                f"** confidence: {format_float(region.confidence)}",
                f"** validation_status: {report.validation_status}",
                f"** solver_{item.set_kind}: {item.set_name}",
            ]
        )
        if item.reuses_native_set:
            lines.append(f"** Reuses preserved native {item.set_kind.upper()} {item.set_name}.")
        else:
            ids = item.node_ids if item.set_kind == "nset" else item.element_ids
            lines.extend(_set_definition(item.set_kind, item.set_name, ids))
        lines.append("")

    lines.extend(
        _set_definition("elset", all_elements_name, tuple(sorted(model.element_ids)))
    )
    lines.extend(
        [
            "",
            f"*MATERIAL, NAME={material_name}",
            "*ELASTIC",
            f"{format_float(intent.materials[0].E_MPa)}, {format_float(intent.materials[0].nu)}",
            f"*SOLID SECTION, ELSET={all_elements_name}, MATERIAL={material_name}",
            "",
            "*STEP, NAME=STATIC_STEP",
            "*STATIC",
        ]
    )

    sorted_bcs = sorted(
        enumerate(intent.bcs),
        key=lambda item: (
            item[1].type,
            item[1].region_ref,
            json.dumps(item[1].model_dump(mode="json"), sort_keys=True),
            item[0],
        ),
    )
    for _, bc in sorted_bcs:
        target = resolved[bc.region_ref]
        lines.extend([f"** {bc.type} on region {bc.region_ref}", "*BOUNDARY"])
        if bc.type == "fixed_displacement":
            for axis in sorted(bc.components, key=lambda value: _AXIS_TO_DOF[value]):
                dof = _AXIS_TO_DOF[axis]
                lines.append(f"{target.set_name}, {dof}, {dof}, 0")
        else:
            for axis, value in sorted(
                bc.components.items(), key=lambda item: _AXIS_TO_DOF[item[0]]
            ):
                dof = _AXIS_TO_DOF[axis]
                lines.append(
                    f"{target.set_name}, {dof}, {dof}, {format_float(value)}"
                )

    sorted_loads = sorted(
        enumerate(intent.loads),
        key=lambda item: (
            item[1].type,
            item[1].region_ref or "",
            json.dumps(item[1].model_dump(mode="json"), sort_keys=True),
            item[0],
        ),
    )
    for _, load in sorted_loads:
        if load.type == "resultant_surface_force":
            target = resolved[load.region_ref]
            lines.extend(
                [
                    f"** resultant_surface_force on {load.region_ref}: equal nodal distribution",
                    "** Total force is preserved component-wise. This is not pressure.",
                    "*CLOAD",
                ]
            )
            distributions = [
                _split_decimal(value, len(target.node_ids)) for value in load.vector
            ]
            for node_index, node_id in enumerate(target.node_ids):
                for component_index, dof in enumerate((1, 2, 3)):
                    value = distributions[component_index][node_index]
                    if value != 0:
                        lines.append(f"{node_id}, {dof}, {_format_decimal(value)}")
        elif load.type == "concentrated_force":
            target = resolved[load.region_ref]
            node_id = target.node_ids[0]
            lines.extend(
                [
                    f"** concentrated_force on the single node in region {load.region_ref}",
                    "*CLOAD",
                ]
            )
            for dof, value in enumerate(load.vector, start=1):
                if float(value) != 0.0:
                    lines.append(f"{node_id}, {dof}, {format_float(value)}")
        elif load.type == "pressure":
            target = resolved[load.region_ref]
            references = _element_faces(target, model)
            lines.extend(
                [
                    f"** pressure on {load.region_ref}: positive magnitude acts into the surface (Task 7 convention)",
                    "*DLOAD",
                ]
            )
            for reference in references:
                pressure_label = "P" + reference.face_label[1:]
                lines.append(
                    f"{reference.element_id}, {pressure_label}, {format_float(load.magnitude)}"
                )
        elif load.type == "gravity":
            if load.region_ref is None:
                target_name = all_elements_name
            else:
                target_name = resolved[load.region_ref].set_name
            magnitude, direction = _magnitude_direction(load.vector)
            lines.extend(
                [
                    f"** gravity vector: {', '.join(format_float(value) for value in load.vector)} mm/s^2",
                    "*DLOAD",
                    (
                        f"{target_name}, GRAV, {format_float(magnitude)}, "
                        f"{format_float(direction[0])}, {format_float(direction[1])}, {format_float(direction[2])}"
                    ),
                ]
            )
        else:  # surface traction is rejected during preflight
            raise UnsupportedLoadTypeError(
                f"CalculiX mapping for load type '{load.type}' is unsupported."
            )

    lines.extend(["*END STEP", ""])
    text = "\n".join(lines)
    filename = f"{safe_artifact_stem(model.inventory.source_name)}_ccx.inp"
    return make_result(
        adapter_name="ccx_inp",
        suggested_filename=filename,
        media_type="text/plain; charset=utf-8",
        artifact_text=text,
        warnings=warnings,
    )


def _preflight(
    intent: SimulationIntent, model: MeshModelMetadata
) -> tuple[dict[str, _ResolvedRegion], str, str, list[str]]:
    if model.inventory.format != "abaqus" or model.source_path.suffix.lower() != ".inp":
        raise UnsupportedModelTypeError("The ccx_inp adapter requires an Abaqus INP mesh model.")
    if model.source_path.name != model.inventory.source_name:
        raise MissingRegionMappingError(
            "The explicit INP path and mesh inventory name do not match."
        )
    if file_checksum(model.source_path) != model.inventory.file_sha256:
        raise MissingRegionMappingError(
            "The explicit INP file no longer matches the inventoried source content hash."
        )
    if not model.node_ids or not model.element_ids:
        raise MissingRegionMappingError("Native mesh node and element IDs are required.")
    if (
        any(isinstance(value, bool) or not isinstance(value, int) or value <= 0 for value in model.node_ids)
        or any(
            isinstance(value, bool) or not isinstance(value, int) or value <= 0
            for value in model.element_ids
        )
        or len(model.node_ids) != len(set(model.node_ids))
        or len(model.element_ids) != len(set(model.element_ids))
    ):
        raise MissingRegionMappingError("Native mesh IDs must be unique.")
    if len(intent.materials) != 1:
        raise MissingMaterialAssignmentError(
            "The current IR can assign material safely only when exactly one material applies to all solid elements."
        )

    resolved: dict[str, _ResolvedRegion] = {}
    warnings: list[str] = []
    used: dict[tuple[str, str], str] = {}
    reserved = {
        "nset": {
            item.name.upper()
            for item in model.inventory.regions
            if item.kind == "node_set"
        },
        "elset": {
            item.name.upper()
            for item in model.inventory.regions
            if item.kind == "element_set"
        },
    }
    for region in sorted(intent.regions, key=lambda item: item.id):
        item, item_warnings = _resolve_region(region, model)
        if (
            not item.reuses_native_set
            and item.set_name.upper() in reserved[item.set_kind]
        ):
            replacement_name = _noncolliding_set_name(
                item.set_kind,
                f"SIM_INT_{region.id}",
                reserved[item.set_kind]
                | {name for kind, name in used if kind == item.set_kind},
            )
            item = replace(item, set_name=replacement_name)
            item_warnings.append(
                f"Region '{region.id}' generated set name was changed to avoid a native-set collision."
            )
        key = (item.set_kind, item.set_name.upper())
        previous = used.get(key)
        if previous is not None and previous != region.id:
            raise MissingRegionMappingError("Two IR regions map to the same solver set name.")
        used[key] = region.id
        reserved[item.set_kind].add(item.set_name.upper())
        resolved[region.id] = item
        warnings.extend(item_warnings)

    for bc in intent.bcs:
        if not resolved[bc.region_ref].node_ids:
            raise UnsupportedEntityTypeError(
                f"Boundary condition region '{bc.region_ref}' does not resolve to mesh nodes."
            )
    for load in intent.loads:
        if load.type == "surface_traction":
            raise UnsupportedLoadTypeError(
                "CalculiX vector surface traction is not mapped by the current adapter; no physics approximation is applied."
            )
        if load.type in {"resultant_surface_force", "concentrated_force"}:
            target = resolved[load.region_ref]
            if not target.node_ids:
                raise UnsupportedEntityTypeError(
                    f"Load region '{load.region_ref}' does not resolve to mesh nodes."
                )
            if load.type == "concentrated_force" and len(target.node_ids) != 1:
                raise InvalidRegionReferenceError(
                    "Concentrated force requires exactly one native node; use resultant_surface_force for a multi-node region."
                )
        elif load.type == "pressure":
            target = resolved[load.region_ref]
            if target.region.entity_type != "mesh_face":
                raise UnsupportedEntityTypeError(
                    "CalculiX pressure requires a mesh_face region with explicit element-face topology."
                )
            _element_faces(target, model)
        elif load.type == "gravity" and load.region_ref is not None:
            target = resolved[load.region_ref]
            if not target.element_ids:
                raise UnsupportedEntityTypeError(
                    "Region-scoped CalculiX gravity requires an element_set region."
                )

    material_name = stable_name("MAT", intent.materials[0].name)
    all_elements_name = _noncolliding_set_name(
        "elset",
        "ALL_ELEMENTS",
        reserved["elset"] | {name for kind, name in used if kind == "elset"},
    )
    return resolved, material_name, all_elements_name, sorted(set(warnings))


def _resolve_region(
    region: Region, model: MeshModelMetadata
) -> tuple[_ResolvedRegion, list[str]]:
    node_universe = set(model.node_ids)
    element_universe = set(model.element_ids)
    native_by_name = {item.name: item for item in model.inventory.regions}
    warnings: list[str] = []

    if region.entity_type in {"node_set", "element_set"}:
        expected_kind = region.entity_type
        values = region.entity_ids
        if all(isinstance(value, int) and not isinstance(value, bool) for value in values):
            ids = tuple(sorted(set(int(value) for value in values)))
            universe = node_universe if expected_kind == "node_set" else element_universe
            if len(ids) != len(values) or any(value not in universe for value in ids):
                raise InvalidRegionReferenceError(
                    f"Region '{region.id}' contains duplicate or unknown native IDs."
                )
            set_name = stable_name("NSET" if expected_kind == "node_set" else "ELSET", region.id)
            return (
                _ResolvedRegion(
                    region=region,
                    set_name=set_name,
                    set_kind="nset" if expected_kind == "node_set" else "elset",
                    node_ids=ids if expected_kind == "node_set" else (),
                    element_ids=ids if expected_kind == "element_set" else (),
                ),
                warnings,
            )
        if not all(isinstance(value, str) and value for value in values):
            raise InvalidRegionReferenceError(
                f"Region '{region.id}' must use all integer IDs or all native set names."
            )
        native_regions = []
        for value in values:
            native = native_by_name.get(str(value))
            if native is None:
                raise InvalidRegionReferenceError(
                    f"Region '{region.id}' references an unknown native set name."
                )
            if native.kind != expected_kind:
                raise InvalidRegionReferenceError(
                    f"Region '{region.id}' references a native set of the wrong entity kind."
                )
            native_regions.append(native)
        ids = tuple(sorted({value for native in native_regions for value in native.ids}))
        universe = node_universe if expected_kind == "node_set" else element_universe
        if not ids or any(value not in universe for value in ids):
            raise InvalidRegionReferenceError(
                f"Region '{region.id}' native set membership is empty or dangling."
            )
        reuse = len(native_regions) == 1 and bool(_SAFE_NATIVE_SET.fullmatch(native_regions[0].name))
        if reuse:
            set_name = native_regions[0].name
        else:
            set_name = stable_name("NSET" if expected_kind == "node_set" else "ELSET", region.id)
            warnings.append(
                f"Region '{region.id}' combines or sanitizes native sets into deterministic set '{set_name}'."
            )
        return (
            _ResolvedRegion(
                region=region,
                set_name=set_name,
                set_kind="nset" if expected_kind == "node_set" else "elset",
                node_ids=ids if expected_kind == "node_set" else (),
                element_ids=ids if expected_kind == "element_set" else (),
                reuses_native_set=reuse,
            ),
            warnings,
        )

    if region.entity_type == "mesh_face":
        if not all(isinstance(value, int) and not isinstance(value, bool) for value in region.entity_ids):
            raise InvalidRegionReferenceError(
                f"Mesh-face region '{region.id}' must contain Task 5 facet-group IDs."
            )
        group_ids = tuple(sorted(set(int(value) for value in region.entity_ids)))
        if len(group_ids) != len(region.entity_ids):
            raise InvalidRegionReferenceError(
                f"Mesh-face region '{region.id}' contains duplicate facet-group IDs."
            )
        facet_ids: set[int] = set()
        node_ids: set[int] = set()
        facets_by_id = {facet.id: facet for facet in model.inventory.facets}
        for group_id in group_ids:
            try:
                group = model.inventory.facet_group(group_id)
            except KeyError:
                raise InvalidRegionReferenceError(
                    f"Mesh-face region '{region.id}' references an unknown facet group."
                ) from None
            for facet_id in group.facet_ids:
                facet = facets_by_id.get(facet_id)
                if facet is None:
                    raise InvalidRegionReferenceError(
                        f"Mesh-face region '{region.id}' contains a dangling facet reference."
                    )
                facet_ids.add(facet_id)
                node_ids.update(facet.node_ids)
        if not node_ids or any(value not in node_universe for value in node_ids):
            raise InvalidRegionReferenceError(
                f"Mesh-face region '{region.id}' does not resolve to valid native nodes."
            )
        return (
            _ResolvedRegion(
                region=region,
                set_name=stable_name("NSET", region.id),
                set_kind="nset",
                node_ids=tuple(sorted(node_ids)),
                facet_ids=tuple(sorted(facet_ids)),
            ),
            warnings,
        )

    raise UnsupportedEntityTypeError(
        f"The ccx_inp adapter does not support region entity type '{region.entity_type}'."
    )


def _element_faces(
    target: _ResolvedRegion, model: MeshModelMetadata
) -> tuple[ElementFaceReference, ...]:
    missing = [
        facet_id
        for facet_id in target.facet_ids
        if facet_id not in model.element_face_by_facet
    ]
    if missing:
        raise MissingMeshTopologyError(
            "Task 5 mesh inventory lacks owner-element/local-face topology for the selected pressure surface."
        )
    references = tuple(
        sorted(
            (model.element_face_by_facet[facet_id] for facet_id in target.facet_ids),
            key=lambda item: (item.element_id, item.face_label),
        )
    )
    allowed_labels = {"S1", "S2", "S3", "S4", "S5", "S6"}
    if any(
        isinstance(item.element_id, bool)
        or not isinstance(item.element_id, int)
        or item.element_id <= 0
        or item.face_label not in allowed_labels
        for item in references
    ):
        raise InvalidRegionReferenceError(
            "Pressure topology contains an invalid native element or local face label."
        )
    if len(references) != len(set((item.element_id, item.face_label) for item in references)):
        raise InvalidRegionReferenceError("Pressure topology contains duplicate element-face references.")
    element_universe = set(model.element_ids)
    if any(item.element_id not in element_universe for item in references):
        raise InvalidRegionReferenceError("Pressure topology references an unknown native element.")
    return references


def _set_definition(kind: str, name: str, ids: tuple[int, ...]) -> list[str]:
    keyword = "*NSET, NSET=" if kind == "nset" else "*ELSET, ELSET="
    lines = [f"{keyword}{name}"]
    for start in range(0, len(ids), 16):
        lines.append(", ".join(str(value) for value in ids[start : start + 16]))
    return lines


def _noncolliding_set_name(kind: str, raw: str, reserved: set[str]) -> str:
    prefix = "NSET" if kind == "nset" else "ELSET"
    candidate = stable_name(prefix, raw)
    if candidate.upper() not in reserved:
        return candidate
    digest = hashlib.sha256(f"{kind}\0{raw}".encode("utf-8")).hexdigest()[:8]
    candidate = stable_name(prefix, f"SIM_INT_{raw}_{digest}")
    if candidate.upper() in reserved:
        raise MissingRegionMappingError(
            "A collision-free deterministic generated set name could not be created."
        )
    return candidate


def _split_decimal(total: float, count: int) -> tuple[Decimal, ...]:
    if count <= 0:
        raise InvalidRegionReferenceError("A resultant-force region contains no nodes.")
    total_decimal = Decimal(str(float(total)))
    if count == 1:
        return (total_decimal,)
    with localcontext() as context:
        context.prec = 28
        share = total_decimal / Decimal(count)
        values = [share] * (count - 1)
        values.append(total_decimal - share * Decimal(count - 1))
    return tuple(values)


def _format_decimal(value: Decimal) -> str:
    if value == 0:
        return "0"
    text = format(value, "f")
    return text.rstrip("0").rstrip(".") if "." in text else text


def _magnitude_direction(vector: list[float]) -> tuple[float, tuple[float, float, float]]:
    magnitude = math.sqrt(sum(float(value) ** 2 for value in vector))
    return magnitude, tuple(float(value) / magnitude for value in vector)  # type: ignore[return-value]


def _comment_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)
