# Generated by sim-intent Task 14.
# Inspect before use. Execution requires an Abaqus Python environment.
# No solver job is created or submitted by this script.
# Analysis: static_structural
# Internal unit convention: mm-N-MPa (gravity acceleration in mm/s^2)
# Server-computed validation status: valid
# Source STEP SHA-256: d81d158aa3b0a5464407496bd1782eba375f853e870fba6edd8cf485825f3c90
# Region mapping: source_step_face_order (OCC tag n -> part.faces[n - 1])
# Mapping is valid only for the exact content-hashed STEP file; regenerated CAD is unsupported.
# Accepted assumptions:
# - [assumption_099adc813874096a] "The 5 kN value was interpreted as total force, not pressure or force per node."
# - [assumption_28387eaa66c82eac] "Downward was interpreted as the negative Y direction of the model coordinate system."

from abaqus import mdb
from abaqusConstants import (DEFORMABLE_BODY, GENERAL, OFF, THREE_D,
                             UNIFORM, UNSET)
import math

MODEL_NAME = 'SIM_INTENT_MODEL'
PART_NAME = 'SIM_INTENT_PART'
INSTANCE_NAME = 'SIM_INTENT_PART_1'
STEP_NAME = 'STATIC_STEP'
STEP_FILE = 'bracket.step'
SOURCE_STEP_SHA256 = 'd81d158aa3b0a5464407496bd1782eba375f853e870fba6edd8cf485825f3c90'

model = mdb.Model(name=MODEL_NAME)
step_geometry = mdb.openStep(fileName=STEP_FILE, scaleFromFile=OFF)
part = model.PartFromGeometryFile(
    name=PART_NAME, geometryFile=step_geometry, combine=False,
    dimensionality=THREE_D, type=DEFORMABLE_BODY)
if len(part.faces) < 12:
    raise RuntimeError('Imported STEP face count cannot satisfy confirmed source face tags.')

# Region ID: "bolt_holes"
# source_instruction: "Fix the two bolt holes."
# original_entity_ids: [11,12]
# selection_method: semantic_geometry_query
# confidence: 0.95
# validation_status: valid
# solver_set: SET_BOLT_HOLES; solver_surface: SURF_BOLT_HOLES
_face_tags = (11, 12)
_faces = tuple(part.faces[tag - 1] for tag in _face_tags)
part.Set(name='SET_BOLT_HOLES', faces=_faces)
part.Surface(name='SURF_BOLT_HOLES', side1Faces=_faces)

# Region ID: "upper_mounting_face"
# source_instruction: "Apply a total downward force of 5 kN to the upper mounting face."
# original_entity_ids: [4]
# selection_method: user_confirmed
# confidence: 1
# validation_status: valid
# solver_set: SET_UPPER_MOUNTING_FACE; solver_surface: SURF_UPPER_MOUNTING_FACE
_face_tags = (4,)
_faces = tuple(part.faces[tag - 1] for tag in _face_tags)
part.Set(name='SET_UPPER_MOUNTING_FACE', faces=_faces)
part.Surface(name='SURF_UPPER_MOUNTING_FACE', side1Faces=_faces)

# Material: "steel" (linear_elastic_isotropic)
material = model.Material(name='MAT_STEEL')
material.Elastic(table=((210000, 0.3),))

if len(part.cells) == 0:
    raise RuntimeError('Imported STEP contains no solid cells for material assignment.')
part.Set(name='ALL_SOLID_CELLS', cells=part.cells[:])
model.HomogeneousSolidSection(name='SECTION_ALL', material='MAT_STEEL', thickness=None)
part.SectionAssignment(region=part.sets['ALL_SOLID_CELLS'], sectionName='SECTION_ALL')
assembly = model.rootAssembly
instance = assembly.Instance(name=INSTANCE_NAME, part=part, dependent=OFF)
model.StaticStep(name=STEP_NAME, previous='Initial')

# fixed_displacement -> Abaqus DisplacementBC on region bolt_holes
model.DisplacementBC(name='BC_001_FIXED_DISPLACEMENT', createStepName=STEP_NAME,
    region=instance.sets['SET_BOLT_HOLES'], u1=0.0, u2=0.0, u3=0.0)

# resultant_surface_force on upper_mounting_face: total vector (0, -5000, 0) N
# Mapping: compute imported area at script runtime, then apply equal general traction.
# This is not a pressure conversion; vector direction is preserved.
_surface = instance.surfaces['SURF_UPPER_MOUNTING_FACE']
_surface_area = sum(face.getSize(printResults=False) for face in _surface.faces)
if _surface_area <= 0.0:
    raise RuntimeError('Confirmed resultant-force surface has non-positive area.')
_traction_magnitude = 5000 / _surface_area
_traction_direction = (0, -1, 0)
model.SurfaceTraction(name='LOAD_001_RESULTANT_SURFACE_FORCE', createStepName=STEP_NAME,
    region=_surface, magnitude=_traction_magnitude, directionVector=((0.0, 0.0, 0.0), _traction_direction),
    distributionType=UNIFORM, traction=GENERAL)
